apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    k8s-app: node-exporter
spec:
  selector:
    matchLabels:
      k8s-app: node-exporter
  template:
    metadata:
      labels:
        k8s-app: node-exporter
    spec:
      containers:
      - image: prom/node-exporter
        name: node-exporter
        ports:
        - containerPort: 9100
          protocol: TCP
          name: http
      tolerations:      # datatransfer용 노드에 배포하기 위한 toleration
      - key: "role"
        operator: "Equal"
        value: "data-transfer"
        effect: "NoSchedule"
      - key: "role"     # gpu용 노드에 배포하기 위한 toleration
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9100
    nodePort: 32100
    protocol: TCP
  type: NodePort
  selector:
    k8s-app: node-exporter
