apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest # 테스트 환경 v0.25.0
        args:
          - "--config.file=/etc/alertmanager/config.yml"
          - "--storage.path=/alertmanager"
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: alertmanager
          mountPath: /alertmanager
        #- name: templates-volume
        #  mountPath: /etc/alertmanager-templates        
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      - name: alertmanager
        nfs:
          path: /monitoring-volume/alertmanager
          server: 10.10.10.69
      #- name: templates-volume
      #  configMap:
      #    name: alertmanager-templates
