---
# mon 서버에서 ceph mon dump 로 fsid, mon ip 확인
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "fsid",
        "monitors": [
          "mon_IP:6789",
          "mon_IP:6789",
          "mon_IP:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
  namespace: ceph-csi
