apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sbw
  name: sbw-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: csi-cephfs-sc
  volumeMode: Filesystem
