- name: Ceph Node Preinstaller
  hosts: all
  gather_facts: false
  tasks:
  - name: Set hosts
    copy:
      src: "./hosts"
      dest: "/etc/hosts"
  - name: Stop firewalld
    service:
      name: firewalld
      state: stopped
      enabled: no
  
  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Add Docker repository
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo 
      dest: /etc/yum.repos.d/
      mode: '0644'
    when: install_package|bool

  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
      skip_broken: yes
  
  - name: Install Packages
    package:
      name:
        - python3
        - chrony
        - net-tools
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      state: latest
  
  - name: Install Docker Package
    package:
      name: "{{docker_package_version}}"
      state: present  
  
  - name: Start chronyd Service
    service:
      name: chronyd
      state: started
      enabled: yes
  
  - name: Start docker Service
    service:
      name: docker
      state: started
      enabled: yes
